# Generated by Django 4.2.11 on 2026-06-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100, verbose_name='Ключ сессии')),
                ('user_message', models.TextField(verbose_name='Сообщение пользователя')),
                ('bot_response', models.TextField(blank=True, verbose_name='Ответ бота')),
                ('is_answered_by_operator', models.BooleanField(default=False, verbose_name='Ответил оператор')),
                ('operator_response', models.TextField(blank=True, verbose_name='Ответ оператора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['-created_at'],
            },
        ),
    ]
