# Generated by Django 4.2.11 on 2026-06-05 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('min_order_amount', models.IntegerField(blank=True, help_text='Минимальная сумма в рублях', null=True, verbose_name='Минимальная сумма заказа (₽)')),
                ('min_order_quantity', models.IntegerField(blank=True, help_text='Минимальное количество в кг или штуках', null=True, verbose_name='Минимальный объём (кг/шт)')),
                ('price_info', models.TextField(blank=True, help_text='Примерные цены или прайс-лист', verbose_name='Информация о ценах')),
                ('delivery_terms', models.TextField(blank=True, help_text='Самовывоз, доставка по городу/региону, стоимость', verbose_name='Условия доставки')),
                ('has_certificates', models.BooleanField(default=False, help_text='Есть ли сертификаты качества, декларации', verbose_name='Наличие сертификатов')),
                ('rating', models.FloatField(default=0.0, help_text='Рассчитывается автоматически из отзывов', verbose_name='Средний рейтинг')),
                ('notes', models.TextField(blank=True, help_text='Внутренние заметки о поставщике', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('categories', models.ManyToManyField(to='suppliers.suppliercategory', verbose_name='Категории товаров')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='suppliers.supplier', verbose_name='Поставщик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('supplier', 'user')},
            },
        ),
    ]
