# Generated by Django 4.2.11 on 2026-06-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
    ]
