# Generated by Django 4.2.11 on 2026-06-03 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('category', models.CharField(choices=[('pizza', '🍕 Пицца'), ('rolls', '🍣 Роллы'), ('salads', '🥗 Салаты'), ('drinks', '🥤 Напитки')], max_length=50, verbose_name='Категория')),
                ('quantity', models.IntegerField(verbose_name='Количество продаж')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выручка')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
