# Generated by Django 4.2.11 on 2026-06-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
